---
- name: show version
  hosts: "ios-devices"
  gather_facts: false
  connection: local

  tasks:
    - name: send configuration commands to IOS
      telnet:
        user: cisco
        password: cisco
        login_prompt: "Username: "
        prompts:
          - "[#]"
        command:
          - terminal length 0
          - configure terminal
          - hostname XR-Router
          - do show version
          - interface gigabitEthernet 0/0/0/0
          - description MGMT
          - commit
          
      register: output

    - name: show output
      debug:
        var: output.stdout

    - name: copy output to file
      copy: 
        content: "{{ output }}" 
        dest: ./output/{{ inventory_hostname }}.json


