---

- name: Enable LLDP
  hosts: "core-devices"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: enable LLDP service
      ios_command:
        commands:
          - lldp run
      
      register: output

    - name: show output
      debug:
        var: output
